name: CI-BudgetManager
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pull BudgetManager Subtree
        run: git subtree pull -P packages/BudgetManager  --squash git@github.com:wanshikaimo/sub.git master
